### ISSUE TITLE
Keep using a single file per class

### ISSUE THREAD

**Issue by ziopod** [michelf/php-smartypants#10]
Hi,
It's embarrasing to use SmartyPantsTypographer with PSR autoloding compliance.
When i want to use `Michelf\SmartyPantsTypographer`

```
 _SmartyPantsTypographer_TmpImpl
```

Could not be found.

Cheer.

**Comment by mosbth** [comment]
Autoloading (when using composer/packagist) seems to work with:

```
        "michelf/php-smartypants": "1.6.x-dev",
```

but _not_ with:

```
        "michelf/php-smartypants": "1.6-beta1",
```

It seems to be a tag 1.6.0-beta1 in the repo, that should work with autoloading, but that version is not visible through packagist. [Review through blaming the composer.json](https://github.com/michelf/php-smartypants/blame/lib/composer.json).

**Comment by michelf** [comment]
There is now a 1.6.0 non-beta version where the `_SmartyPantsTypographer_TmpImpl` class has been removed. 

Sorry for not replying to this earlier. The following information applies to 1.6-beta1 and is basically outdated, but it tries to explain things. You weren't supposed to use the `_SmartyPantsTypographer_TmpImpl` class, it was a temporary implementation detail to keep the implementation for both parsers classes in the same file so I could keep merging the previous package format using git without too much fuss. The `SmartyPantsTypographer` class should have been used instead. It was in its own file, worked with auto-loading and is basically an empty subclass of `_SmartyPantsTypographer_TmpImpl`. I should have made that clearer, perhaps by making `_SmartyPantsTypographer_TmpImpl` abstract.
