### ISSUE TITLE
3 dashes don't turn into a em-dash

### ISSUE THREAD

**Issue by alsciende** [michelf/php-smartypants#11]
3 consecutive dashes turn into a en-dash followed by a dash instead of a em-dash.

```
php -r "include 'vendor/michelf/php-smartypants/Michelf/SmartyPants.php'; echo Michelf\SmartyPants::defaultTransform('--');"
>> &#8212;

php -r "include 'vendor/michelf/php-smartypants/Michelf/SmartyPants.php'; echo Michelf\SmartyPants::defaultTransform('---');"
>> &#8212;-
```

**Comment by michelf** [comment]
You probably want to use the [`SMARTYPANTS_ATTR_LONG_EM_DASH_SHORT_EN`](https://github.com/michelf/php-smartypants/blob/lib/Michelf/SmartyPants.php#L23) as the second attribute to `defaultTransform`.

**Comment by alsciende** [comment]
Thank you. My bad for not reading the documentation.
