### ISSUE TITLE
Configurable punctuation marks

### ISSUE THREAD

**Issue by mingos777** [michelf/php-smartypants#12]
The punctuation marks used to replace quotation marks (") are not consistent between languages. In Polish, we use a different opening quotation mark at the bottom of the line: `&#8222;` („quotation”).

Thus, being able to configure the replacement punctuation marks rather than relying on the defaults would be spot on. This has been addressed in the [Python extension to Markdown](https://pythonhosted.org/Markdown/extensions/smarty.html) which I use in a different project. Would it be possible to have similar behaviour in your tool?

**Comment by michelf** [comment]
``` php
$parser = new \Michelf\SmartyPantsTypographer()
$parser->smart_doublequote_open = "&#8222;";
echo $parser->transform('Hello "Dominik"');
```

**Comment by mingos777** [comment]
Oh, neat! Seems I should've dug deeper into the docs before creating an issue. Thanks a million!
