### ISSUE TITLE
Upgrade version number to include autoloader instruction to packagist

### ISSUE THREAD

**Issue by mosbth** [michelf/php-smartypants#14]
Its currently only the dev-version that includes the correct composer.json to enable the autoloader.

One can require the dev-version.

But when you have a package (A), that depends on some package (B) that depends on php-smartypants (C). It will not be enough for B to include C in composer.json, even A needs to include C. This is due to the dev-version.

Tag a new version, v1.6.1 and it will be enough for B to include C, A does not need to know what B depends on.

**Comment by michelf** [comment]
The latest version is now 1.6.0, and no longer a beta. Sorry for the wait.
