### ISSUE TITLE
Error , Undefined property

### ISSUE THREAD

**Issue by maxiz22** [michelf/php-smartypants#16]
Undefined property: Michelf\SmartyPantsTypographer::$backtick_doublequote

`
LINE 385 \vendor\michelf\php-smartypants\Michelf\SmartyPants.php
 
        $_ = str_replace(array("``", "''",),
                         array($this->backtick_doublequote,
                               $this->apostrophe_doublequote), $_);
        return $_;
    }
 
`

**Comment by michelf** [comment]
Thanks. That thing slipped in the previous release.
