### ISSUE TITLE
Coding standards and phpdoc

### ISSUE THREAD

**Issue by lsolesen** [michelf/php-smartypants#2]
I would volunteer to run php-smartypant through

```
phpcs
```

to have it adhere to some common coding standards and make the inline documentation compatible with phpdoc.

Would you accept pull requests on that?

**Comment by michelf** [comment]
Please refer to [similar discussion about PHP Markdown](https://github.com/michelf/php-markdown/issues/issue/2).

**Comment by lsolesen** [comment]
Allright.
