### ISSUE TITLE
Possibly applying within <style> tags

### ISSUE THREAD

**Issue by alanhogan** [michelf/php-smartypants#20]
I haven't checked to see if I am using the current version, sorry, but it seems to be messing up CSS such as `padding: 0 0 12px 0` when the `<style>` tag is within `body`.

I am about to fall asleep or I would check the current version explicitly

**Comment by michelf** [comment]
This:
```
<h1>"Boo"</h1>
<style>body { font: "boo" }</style>
```
produces the expected result for me:
```
<h1>&#8220;Boo&#8221;</h1>
<style>body { font: "boo" }</style>
```
Do you have a more specific example?

You can try it on the [dingus](https://michelf.ca/projects/php-markdown/dingus/) (select the PHP SmartyPants filter).

**Comment by alanhogan** [comment]
Yeah, this is surely caused by me being on an old version.

The dingus correctly processes the example that was messing me up:

```html
<style type="text/css">
#foo input {
	padding: 0 0.2em;
}
</style>
```

which was getting mangled into:

```html
<style type="text/css">
#foo input {
	padding: 0&#160;0.2em;
}
</style>
```

I was on version "1.5.1oo2" apparently

Sorry, I really shouldn't have opened an issue. I was half falling asleep and not thinking very straight.
